SELECT
    TABLE_NAME AS NombreTabla,
    COUNT(COLUMN_NAME) AS NumColumnas,
    SUM(CASE WHEN nullable = 'Y' THEN 1 ELSE 0 END) AS NumColsNull,
    MAX(LAST_ANALYZED) AS Último_Análisis
FROM ALL_TAB_COLS
WHERE owner = 'PARRANDEROS'
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;