SELECT
    TABLE_NAME AS NombreTabla,
    DATA_TYPE AS TipoDeDato,
    COUNT(DATA_TYPE) AS NumColsTipoDato,
    ROUND(AVG(DATA_LENGTH),2) AS PromedioLongitudCol
FROM ALL_TAB_COLS
WHERE owner = 'PARRANDEROS'
GROUP BY TABLE_NAME, DATA_TYPE
ORDER BY TABLE_NAME, DATA_TYPE;
