SELECT
    'SELECT TABLE_NAME, COLUMN_NAME, COUNT(CONSTRAINT_NAME) ' ||
    'FROM ALL_CONS_COLUMNS ' ||
    'WHERE OWNER = ''PARRANDEROS'' AND ' ||
    'TABLE_NAME = ''' || TABLE_NAME ||''' AND ' ||
    'COLUMN_NAME = ''' || COLUMN_NAME || ''' ' ||
    'GROUP BY TABLE_NAME, COLUMN_NAME;'
    
FROM
    ALL_TAB_COLS
    
WHERE
    OWNER = 'PARRANDEROS' AND
    COLUMN_NAME NOT LIKE '%R%' AND
    REGEXP_COUNT(COLUMN_NAME, '[AEIOUaeiou]') <= 2
;