SELECT
    TABLE_NAME AS NOMBRETABLA,
    COLUMN_NAME AS NOMBRECOLSPK,
    DATA_TYPE AS TIPODEDATO
    
    
FROM
    ALL_CONS_COLUMNS
    NATURAL INNER JOIN
    ALL_TAB_COLS
    
WHERE
    OWNER = 'PARRANDEROS' AND
    CONSTRAINT_NAME LIKE 'PK_%'
    
ORDER BY
    TABLE_NAME ASC,
    COLUMN_NAME ASC
;